.TH MYSTRNCAT 3
.SH NAME
mystrncat \- Append two strings.

.SH SYNOPSIS
.B int mystrncat(char* dest, const char* src);

.SH DESCRIPTION
The mystrncat() appends the source string to the end of destination string.

.SH RETURN VALUE
Returns the integer showing the result of the function.

.SH EXAMPLE
.B int result = mystrncat(dest, src);

.SH AUTHOR
.B SAMI ULLAH
sami1234@gmail.com