.TH MYSTRCPY 3
.SH NAME
mystrcpy \- Creat a copy of string

.SH SYNOPSIS
.B int mystrcpy(char* dest, const char* src);

.SH DESCRIPTION
The mystrcpy() calculate sthe length of string from source to destination.

.SH RETURN VALUE
Returns the integer showing the result of the function.

.SH EXAMPLE
.B int result = mystrcpy(dest, src);

.SH AUTHOR
.B SAMI ULLAH
sami1234@gmail.com