.TH MYSTRNCPY 3
.SH NAME
mystrncpy \- Creat specified numbers of characters of string.

.SH SYNOPSIS
.B int mystrncpy(char* dest, const char* src, int n);

.SH DESCRIPTION
The mystrncpy() copy the specified length of string from source to destination.

.SH RETURN VALUE
Returns the integer showing the result of the function.

.SH EXAMPLE
.B int result = mystrncpy(dest, src,5);

.SH AUTHOR
.B SAMI ULLAH
sami1234@gmail.com