.TH MYSTRLEN 3
.SH NAME
mystrlen \- Calculate the length of string

.SH SYNOPSIS
.B int mystrlen(const char* s);

.SH DESCRIPTION
The mystrlen() calculate sthe length of string pointed to by s.

.SH RETURN VALUE
Returns the number of characters in string.

.SH EXAMPLE
.B int length = mystrlen("length");

.SH AUTHOR
.B SAMI ULLAH
sami1234@gmail.com